### ISSUE TITLE
Multifile torrent missing content

### ISSUE THREAD

**Issue by billotronic** [sayem314/torrenter#1]
Snatched a 2 CD torrent and only CD1 was moved to downloads.

```
╔══════════════════════════════════════════════════════════╗
║                  torrenter (1.0.1)                       ║
╠══════════════════════════════════════════════════════════╣
 ♥  REPO   ║ https://github.com/sayem314/torrenter         ║
╠══════════════════════════════════════════════════════════╣
 ♥  DONATE ║ https://sayem.eu.org/donate                   ║
╚══════════════════════════════════════════════════════════╝
? Search torrent: › (node:17319) Warning: N-API is an experimental feature and could change at any time.
✔ Search torrent: … a space travesty

…  awaiting  Searching for a space travesty
ℹ  info      Found 10 torrents

✔ Select a torrent: › 2001 A Space Travesty (2002) Comedy

 2001 A Space Travesty (2002) Comedy
 ├── 2001 A Space Travesty (Speedy Rip) CD1.avi (656.27 MB)
 ├── 2001 A Space Travesty (Speedy Rip) CD2.avi (655.55 MB)

 Connected  : 2 peers
 Downloaded : 1311.82 MB (549.60 KB/s)
 Uploaded   : 0 Bytes (0 Bytes/s)
 Ratio      : 0.00
 Size       : 1311.82 MB
 ETA        : 0m 00s
 [=========================] 100.00%

✔  success   File saved in downloads

```

```
/downloads/2001 A Space Travesty (2002) Comedy$ ls
'2001 A Space Travesty (Speedy Rip) CD1.avi'

```

**Comment by sayem314** [comment]
torrenter does not move or touch any file, it uses webtorrent to download all included files. Btw I have tested with your query and it seems to be working fine for me at least. If you can re-produce please comment here.

![Screenshot from 2020-01-18 16-59-24](https://user-images.githubusercontent.com/14138401/72662693-34ee2280-3a14-11ea-9667-d5a30cc69f65.png)

**Comment by billotronic** [comment]
Well truth be known I'm getting some really strange behavior now where single files are not showing up at all in /downloads even though I'm watching it dl in the terminal. Is there any way of debugging what is going on with this? Sorry, not all that familiar with node.

**Comment by sayem314** [comment]
Are you using any kind of tool that scan files and does stuff? Also, can you paste output of this command and magnet/torrent link?

`curl -Lso tinfo git.io/bench.sh; bash tinfo -info; rm tinfo`

**Comment by billotronic** [comment]
No pretty vanilla linux.

`curl -Lso tinfo git.io/bench.sh; bash tinfo -info; rm tinfo

 ## System Information

 OS Name     : Bodhi Linux 5 (64 bit)
 Kernel      :  / 4.15.0-20-generic
 Hostname    : spiderskullisland
 CPU Model   : AMD FX(tm)-8350 Eight-Core Processor
 CPU Cores   : 8 cores @  1646.742 MHz
 CPU Cache   : 2048 KB
 Total RAM   : 8005 MiB (Free 3742 MiB)
 Total SWAP  : 28608 MiB (Free 28311MiB)
 Total Space : 215GB (80% used)
 Running for : 21hrs 22min 14sec

`


[magnet:?xt=urn:btih:3EDDBFD0186A7E67A453AB778624547B8CD27AC9&dn=%5Bzooqle.com%5D%20Billy%20Connolly%20High%20Horse%20Tour%202016%20BDRip%20x264%20mkv&tr=http://bt1.archive.org:6969/announce&tr=http://bt2.archive.org:6969/announce&tr=http://open.acgtracker.com:1096/announce&tr=http://tracker.etree.org:6969/announce&tr=http://tracker.tntvillage.scambioetico.org:2710/announce&xl=531217555&tr=udp%3A%2F%2Feddie4.nl%3A6969&tr=udp%3A%2F%2Ftracker.openbittorrent.com%3A80&tr=udp%3A%2F%2Ftracker.coppersurfer.tk%3A6969&tr=http%3A%2F%2Fanisource.net%2Fannounce&tr=udp%3A%2F%2Fp4p.arenabg.ch%3A1337](url)

Same works just fine in qbittorrent.

**Comment by sayem314** [comment]
![Screenshot from 2020-01-18 22-32-54](https://user-images.githubusercontent.com/14138401/72667114-86150b00-3a42-11ea-8197-785d1b8cd54d.png)

I'm not sure anymore, tried with different OS (Bodhi Linux excluded) and all seems to be fine.

**Comment by sayem314** [comment]
Btw, downloads are not saved in `/downloads` but `$(pwd)/downloads`

**Comment by billotronic** [comment]
Something else must be borked on this system then cause I cannot make any rhyme or reason of it either. Thanks for trying to help. The app is super slick.
